#!/usr/bin/python

import time
import os
import sys
import setinputxml
import queryinfoxml
from lxml import etree
import tstamp_folder
import amoeba



def read_optimize_input():
    conf = open("optimize.config","r")
    lines = []

    for line in conf:
        lines.append(line.split())
        
    print lines
    runpath = lines[0][0].strip('"')
    resultspath = lines[1][0].strip('"')
    inputtemplatepath = lines[2][0].strip('"')
    runcommand = "  ".join(lines[3]).strip('"')
    ftolerance = lines[4][0]
    xtolerance = lines[5][0]
    itmax = lines[6][0]

    vararr=[]
    ndata = len(lines)
    for i in range(7,ndata):
        vararr.append([str(lines[i][0]).strip('"'),float(lines[i][1]),float(lines[i][2])])
    
    return runpath,resultspath,inputtemplatepath,runcommand,ftolerance,xtolerance,itmax,vararr

def optimize(runpath,resultspath,inputtemplatepath,vararr,runcommand,ftolerance=1.e-4,xtolerance=1.e-4,itmax=500):
    amoebalog = open(resultspath+"/amoeba.log","w+")
    optimizelog = open(resultspath+"/optimize.log","w+")
    optimizelog.write("runpath  "+runpath+"\n")
    optimizelog.write("resultspath  "+resultspath+"\n")
    optimizelog.write("inputtemplatepath  "+inputtemplatepath+"\n")
    
    optimizelog.write("Variables:\n")
    
    inputtree = etree.parse(inputtemplatepath)
    inputdscr = "Input file generated by script optimize.py \n"
    inputdscr = inputdscr + "runpath: %s\n"%(runpath)
    inputdscr = inputdscr + "resultspath: %s\n"%(resultspath)
    inputdscr = inputdscr + "input template from path: %s\n"%(inputtemplatepath)
    inputdscr = inputdscr + "optimization varibales:\n"

    for var in vararr:
        optimizelog.write("xpath: "+var[0]+"\n")
        optimizelog.write("guess: "+str(var[1])+"\n")
        optimizelog.write("scale: "+str(var[2])+"\n")
        inputdscr = inputdscr + "xpath: "+str(var[0])+"\n"
        inputdscr = inputdscr + "guess: "+str(var[1])+"\n"
        inputdscr = inputdscr + "scale: "+str(var[2])+"\n"

    optimizelog.flush()

    setinputxml.setByXpath(inputtree,"/input/keywords",inputdscr)
    inputtree.write(runpath+"/input.xml",pretty_print="true")

    guess = []
    scale = []
    data = []
    data.append(runpath)
    data.append(runcommand)
    data.append([])
    for var in vararr:
        data[-1].append(var[0]) # build xpath array
        guess.append(var[1]) # build array of initial guess values for the variables
        scale.append(var[2])
 
    simplex,fvalue,iteration = amoeba.amoeba(guess,scale,energy,ftolerance,xtolerance,itmax,data,amoebalog)

    amoebalog.write("%d\t"%(iteration))
    amoebalog.write("%1.10f\t"%(fvalue))
    for value in simplex:
        amoebalog.write("%1.10f\t"%(value))
    amoebalog.write("\n")
    amoebalog.flush()

    optimizelog.write("\nOptimization converged after %d iterations of amoeba.py\n"%(iteration))
    optimizelog.write("\nOptimized variables found:\n")
    for i,var in enumerate(vararr):
        optimizelog.write("xpath: "+var[0]+"\n")
        optimizelog.write("optimized value: %1.0f\n\n"%(simplex[i]))

    optimizelog.flush()

    optimizelog.close()
    amoebalog.close()



def energy(var, data):
    runpath = data[0]
    runcommand = data[1]
    xpath = data[2]
    
    os.chdir(runpath)
    os.system("rm -f info.xml")
   
    
    inputtree = etree.parse("input.xml")

    nvar = len(var)

    for i in range(nvar):
        setinputxml.setByXpath(inputtree,xpath[i],str(var[i]))

    inputtree.write("input.xml",pretty_print="true")

    
    os.system(runcommand)
    
    while not os.path.exists("info.xml"):
        time.sleep(1)

    time.sleep(5)
    return -queryinfoxml.getLastTotalEnergy()


runpath,resultspath,inputtemplatepath,runcommandstring,ftolerance,xtolerance,itmax,vararr = read_optimize_input()

print "runpath: ",runpath
print "resultspath: ",resultspath
print "inputtemplatepath: ",inputtemplatepath
print "runcommand: ",runcommandstring
print "ftolerance: ",ftolerance
print "xtolerance: ",xtolerance
print "itmax: ",itmax
for var in vararr:
    print "+ xpath: "+var[0]
    print "  -guess: "+str(var[1])
    print "  -scale: "+str(var[2])

runpath,sstamp = tstamp_folder.tstamp_folder(runpath)
optimize(runpath,resultspath,inputtemplatepath,vararr,runcommandstring,ftolerance=1.e-2,xtolerance=1.e-2,itmax=500)

