import time
import os
import sys
import setinputxml
import queryinfoxml
from lxml import etree
import tstamp_folder
import amoeba

def optimize(runpath,resultspath,inputtemplatepath,vararr,runcommand,ftolerance=1.e-4,xtolerance=1.e-4,itmax=500):
    amoebalog = open(resultspath+"/amoeba.log","w+")
    optimizelog = open(resultspath+"/optimize.log","w+")
    optimizelog.write("runpath  "+runpath+"\n")
    optimizelog.write("resultspath  "+resultspath+"\n")
    optimizelog.write("inputtemplatepath  "+inputtemplatepath+"\n")
    
    optimizelog.write("Variables:\n")
    
    inputtree = etree.parse(inputtemplatepath)
    inputdscr = "Input file generated by script optimize.py \n"
    inputdscr = inputdscr + "runpath: %s\n"%(runpath)
    inputdscr = inputdscr + "resultspath: %s\n"%(resultspath)
    inputdscr = inputdscr + "input template from path: %s\n"%(inputtemplatepath)
    inputdscr = inputdscr + "optimization varibales:\n"

    for var in vararr:
        optimizelog.write("xpath: "+var[0]+"\n")
        optimizelog.write("guess: "+str(var[1])+"\n")
        optimizelog.write("scale: "+str(var[2])+"\n")
        inputdscr = inputdscr + "xpath: "+str(var[0])+"\n"
        inputdscr = inputdscr + "guess: "+str(var[1])+"\n"
        inputdscr = inputdscr + "scale: "+str(var[2])+"\n"

    optimizelog.flush()

    setinputxml.setByXpath(inputtree,"/input/keywords",inputdscr)
    inputtree.write(runpath+"/input.xml",pretty_print="true")

    guess = []
    scale = []
    data = []
    data.append(runpath)
    data.append(runcommand)
    data.append([])
    for var in vararr:
        data[-1].append(var[0]) # build xpath array
        guess.append(var[1]) # build array of initial guess values for the variables
        scale.append(var[2])
 
    amoeba.amoeba(guess,scale,energy,ftolerance,xtolerance,itmax,data,amoebalog)

    optimizelog.close()
    amoebalog.close()



def energy(var, data):
    runpath = data[0]
    runcommand = data[1]
    xpath = data[2]
    
    os.chdir(runpath)
    os.system("rm -f info.xml")
    
    inputtree = etree.parse("input.xml")

    nvar = len(var)

    for i in range(nvar):
        setinputxml.setByXpath(inputtree,xpath[i],str(var[i]))

    inputtree.write("input.xml",pretty_print="true")

    
    os.system(runcommand)
    
    while not os.path.exists("info.xml"):
        time.sleep(1)

    return -queryinfoxml.getLastTotalEnergy()


runpath,sstamp = tstamp_folder.tstamp_folder("/home1/srigamonti/projects/cobalt_bulk/runs")
resultspath = "/home1/srigamonti/projects/cobalt_bulk/results/optimizeunitcell"
inputtemplatepath = "/home1/srigamonti/projects/cobalt_bulk/runs/1345479936227/input.xml"
vararr = []
vararr.append(["/input/structure/crystal/@scale",4.74,0.05])
vararr.append(["/input/structure/crystal/basevect[3][3]",1.623,0.05])
runcommandstring = "mpi.py 2 12"

optimize(runpath,resultspath,inputtemplatepath,vararr,runcommandstring,ftolerance=1.e-2,xtolerance=1.e-2,itmax=500)

