import time
import os
import sys
import setinput
from lxml import etree


def tstamp_folder(rpath):
    sstamp = str(int(time.time()*1000))
    if rpath[-1]!="/":
        rpath=rpath+"/"
    os.system("mkdir %s"%(rpath+sstamp))
    return rpath+sstamp,sstamp


def sweep(runspath,resultspath,inputtemplatepath,sweepdicarr):
    sweeplog = open(resultspath+"/sweep.log","w+")
    sweeplog.write("runspath  "+runspath+"\n")
    sweeplog.write("resultspath  "+resultspath+"\n")
    sweeplog.write("inputtemplatepath  "+inputtemplatepath+"\n")
    
    rundirlog = open(resultspath+"/rundir.log","w+")
   
   
    inputtree = etree.parse(inputtemplatepath)

    for irun, sweepdic in enumerate(sweepdicarr):
        runpath, rundir = tstamp_folder(runspath)
        os.chdir(runpath)
        sweeplog.write("\n"+"runpath  "+runpath+"\n")
        rundirlog.write(runpath+"\n")

        inputdscr="Input file generated by sweep.py script\n"
        inputdscr=inputdscr+"input.xml template in: %s\n"%(inputtemplatepath)
        inputdscr=inputdscr+"results path is: %s\n"%(resultspath)


        for xpath,value in sweepdic.items():
            sweeplog.write("\t"+"sweepvar  "+xpath+"\n")
            sweeplog.write("\t"+"value  "+value+"\n")

            inputdscr=inputdscr+"sweeping variable: "+xpath+"\n"
            inputdscr=inputdscr+"value: "+value+"\n"
            
            setinput.setbyxpath(inputtree,xpath,value)
        
        setinput.setbyxpath(inputtree,"/input/keywords",inputdscr)

        inputtree.write(runpath+"/input.xml",pretty_print="true")
        
        
    sweeplog.close()
    rundirlog.close()

runspath="/home1/srigamonti/projects/cobalt_bulk/runs"
resultspath="/home1/srigamonti/projects/cobalt_bulk/results/sweepnempty"
inputtemplatepath="/home1/srigamonti/projects/cobalt_bulk/runs/1345479936277/input.xml"
sweepdicarr=[]
sweepdicarr.append({"/input/groundstate/@nempty":"1"})
sweepdicarr.append({"/input/groundstate/@nempty":"2"})
sweepdicarr.append({"/input/groundstate/@nempty":"3"})
sweepdicarr.append({"/input/groundstate/@nempty":"4"})
sweepdicarr.append({"/input/groundstate/@nempty":"5"})
sweepdicarr.append({"/input/groundstate/@nempty":"6"})
sweepdicarr.append({"/input/groundstate/@nempty":"7"})
sweepdicarr.append({"/input/groundstate/@nempty":"8"})
sweepdicarr.append({"/input/groundstate/@nempty":"9"})
sweepdicarr.append({"/input/groundstate/@nempty":"10"})


sweep(runspath,resultspath,inputtemplatepath,sweepdicarr)



